package Source;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
/**
 *
 * @author gargp
 */
public class BookTickets2 extends javax.swing.JFrame {

    /**
     * Creates new form BookTickets2
     */
    public BookTickets2() {
        initComponents();

    }

    public BookTickets2(String City, String Movie, String custid) {
        initComponents();
        Mo.setText(Movie);
        Ci.setText(City);
        Custid.setText("" + custid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Mo = new javax.swing.JLabel();
        Ci = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CiCo = new javax.swing.JComboBox<>();
        T1 = new javax.swing.JRadioButton();
        T2 = new javax.swing.JRadioButton();
        T3 = new javax.swing.JRadioButton();
        T4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        Custid = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Mo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Mo.setForeground(new java.awt.Color(255, 255, 255));
        Mo.setText("<Movie Name>");

        Ci.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Ci.setForeground(new java.awt.Color(204, 204, 204));
        Ci.setText("<City Name>");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        CiCo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Cinema", "Inox", "PVR", "Cinepolis", "BigCinemas" }));
        CiCo.setBorder(null);

        T1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(T1);
        T1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T1.setForeground(new java.awt.Color(255, 255, 255));
        T1.setText("9:00am");

        T2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(T2);
        T2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T2.setForeground(new java.awt.Color(255, 255, 255));
        T2.setText("12:00pm");

        T3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(T3);
        T3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T3.setForeground(new java.awt.Color(255, 255, 255));
        T3.setText("4:00pm");

        T4.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(T4);
        T4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        T4.setForeground(new java.awt.Color(255, 255, 255));
        T4.setText("8:00pm");

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("Day");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField1MousePressed(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/aaa.png"))); // NOI18N
        back.setToolTipText("Go back to Homepage and Logout");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(153, 153, 153))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Ci)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(Mo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(back)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Custid)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(T3)
                            .addComponent(T4)
                            .addComponent(T2)
                            .addComponent(T1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CiCo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Custid)
                    .addComponent(back))
                .addGap(18, 18, 18)
                .addComponent(Mo)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(CiCo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(T1)
                        .addGap(18, 18, 18)
                        .addComponent(T2)
                        .addGap(18, 18, 18)
                        .addComponent(T3)
                        .addGap(18, 18, 18)
                        .addComponent(T4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ci))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean a = true;
        int da;

        String c = jTextField1.getText();
        if (c.equals("") || c.equals("Choose Date")) {
            da = 0;
        } else {
            da = Integer.parseInt(c);
        }
        if (CiCo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select a cinema first!");
        } else if (da <= 0 || da > 31) {
            JOptionPane.showMessageDialog(this, "Please Choose a Valid Date!");
        } else if (jComboBox1.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please Select a Month!");
        } else if (T1.isSelected() == false && T2.isSelected() == false && T3.isSelected() == false && T4.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Please select a time first!");
        } else {
            int ciid = CiCo.getSelectedIndex();
            int tiid = 1;
            if (T1.isSelected() == true) {
                tiid = 1;
            } else if (T2.isSelected() == true) {
                tiid = 2;
            } else if (T3.isSelected() == true) {
                tiid = 3;
            } else if (T4.isSelected() == true) {
                tiid = 4;
            }
            String tiid1 = ""+tiid;
            String ciid1  = ""+ciid;
            System.out.println("" + tiid1);
            System.out.println("" + ciid1);
            System.out.println("" + da);
            System.out.println("" + jComboBox1.getSelectedIndex());
            String custid = Custid.getText();
            String dat = "";
            if (da < 10) {
                dat = "0" + da;
            } else {
                dat = "" + da;
            }

            String MovName = Mo.getText();
            try {

                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kleon", "root", "");

                Class.forName("java.sql.DriverManager");

                String sql4;

                sql4 = " select MovieID from movies where MovieName='" + MovName + "'";
                System.out.println(""+sql4);
                Statement st4 = con.createStatement();
                ResultSet rs4 = st4.executeQuery(sql4);
                rs4.next();
                int MovieId = Integer.parseInt(rs4.getString("MovieID"));

                String month;
                int lmn = jComboBox1.getSelectedIndex();
                if (lmn < 10) {
                    month = "0" + lmn;
                } else {
                    month = "" + lmn;
                }
                
                String Show = tiid1 + ciid1 + dat + month + MovieId;
                long ShowId = Long.parseLong(Show);
                System.out.println(""+ShowId);
                System.out.println(""+Show);
              
               
                String sql8="Update temp set ShowId='"+ShowId+"', MovieId='"+MovieId+"', MovieName='"+MovName+"' where CustUsername='"+custid+"'";
                Statement st8=con.createStatement();
                st8.executeUpdate(sql8);
                        System.out.println(""+sql8);
                
                
                
                
                new selectseat(custid, ShowId).setVisible(true);
                
            } catch (ClassNotFoundException | SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Error:  " + e.getMessage());
            }
            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MousePressed
        jTextField1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1MousePressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        new Start().setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_backMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookTickets2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookTickets2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookTickets2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookTickets2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BookTickets2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ci;
    private javax.swing.JComboBox<String> CiCo;
    private javax.swing.JLabel Custid;
    private javax.swing.JLabel Mo;
    private javax.swing.JRadioButton T1;
    private javax.swing.JRadioButton T2;
    private javax.swing.JRadioButton T3;
    private javax.swing.JRadioButton T4;
    private javax.swing.JLabel back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
