package Source;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gargp
 */
public class PaymentGateway extends javax.swing.JFrame {

    /**
     * Creates new form PaymentGateway
     */
    public PaymentGateway() {
        initComponents();
        int cost = 1000;//Get cost from previous form
        jLabel4.setText("" + cost);
        Banking.setVisible(false);
        CredDeb.setVisible(false);
        TPP.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        R1 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        R2 = new javax.swing.JRadioButton();
        R3 = new javax.swing.JRadioButton();
        R4 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Banking = new javax.swing.JComboBox<>();
        TPP = new javax.swing.JComboBox<>();
        CredDeb = new javax.swing.JComboBox<>();
        back = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/gree.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 51));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total:");

        R1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(R1);
        R1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        R1.setForeground(new java.awt.Color(255, 255, 255));
        R1.setText("Pay on Arrival");
        R1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                R1MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Choose Payment Method:");

        R2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(R2);
        R2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        R2.setForeground(new java.awt.Color(255, 255, 255));
        R2.setText("Credit/Debit Card");
        R2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                R2MousePressed(evt);
            }
        });

        R3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(R3);
        R3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        R3.setForeground(new java.awt.Color(255, 255, 255));
        R3.setText("NetBanking");
        R3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                R3MousePressed(evt);
            }
        });

        R4.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(R4);
        R4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        R4.setForeground(new java.awt.Color(255, 255, 255));
        R4.setText("Third party payment methods");
        R4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                R4MousePressed(evt);
            }
        });

        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Banking.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Service", "SBI", "HDFC", "Kotak Mahindra", "CitiBank" }));
        jLayeredPane1.add(Banking);
        Banking.setBounds(0, 0, 110, 30);

        TPP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Service", "Amazon Pay", "PayTM", "Google Tez" }));
        jLayeredPane1.add(TPP);
        TPP.setBounds(0, 0, 110, 30);

        CredDeb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Service", "VISA", "AmericanExpress", "MasterCard" }));
        jLayeredPane1.add(CredDeb);
        CredDeb.setBounds(0, 0, 110, 30);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/aaa.png"))); // NOI18N
        back.setToolTipText("Go back to Homepage and Logout");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(R1)
                                .addGap(34, 34, 34)
                                .addComponent(R2)
                                .addGap(18, 18, 18)
                                .addComponent(R3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)
                        .addGap(221, 221, 221)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(R4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jButton2)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)))
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R4)
                    .addComponent(R3)
                    .addComponent(R1)
                    .addComponent(R2))
                .addGap(39, 39, 39)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void R1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_R1MouseClicked

        Banking.setVisible(false);
        CredDeb.setVisible(false);
        TPP.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_R1MouseClicked

    private void R2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_R2MousePressed
        CredDeb.setVisible(true);
        Banking.setVisible(false);
        TPP.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_R2MousePressed

    private void R3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_R3MousePressed
        Banking.setVisible(true);
        CredDeb.setVisible(false);
        TPP.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_R3MousePressed

    private void R4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_R4MousePressed
        Banking.setVisible(false);
        CredDeb.setVisible(false);
        TPP.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_R4MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (R1.isSelected() == false && R2.isSelected() == false && R3.isSelected() == false && R4.isSelected() == false) {
        JOptionPane.showMessageDialog(this,"Please Select a Payment Method");   
        }
        else{
        
        
        if(CredDeb.getSelectedIndex()==0 && R2.isSelected()==true){
            JOptionPane.showMessageDialog(this,"Please Select a service");
        } 
        else if(Banking.getSelectedIndex()==0 && R3.isSelected()==true){
            JOptionPane.showMessageDialog(this,"Please Select a service");
        }
        else if(TPP.getSelectedIndex()==0 && R4.isSelected()==true){
            JOptionPane.showMessageDialog(this,"Please Select a service");
        }
        else{
         new ProcessingPayment().setVisible(true);
        this.dispose();// TODO add your handling code here:
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        new Start().setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_backMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentGateway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentGateway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentGateway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentGateway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PaymentGateway().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Banking;
    private javax.swing.JComboBox<String> CredDeb;
    private javax.swing.JRadioButton R1;
    private javax.swing.JRadioButton R2;
    private javax.swing.JRadioButton R3;
    private javax.swing.JRadioButton R4;
    private javax.swing.JComboBox<String> TPP;
    private javax.swing.JLabel back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
