package Source;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
/**
 *
 * @author gargp
 */
public class Snacks extends javax.swing.JFrame {

    Double amount = 0.0;
    String custid = "1", movieid = "1", showid = "1";

    public Snacks() {
        initComponents();

      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        a = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Popc = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        TA = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        Combo = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        Snacks = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        Drinks = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CPI = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        Bill = new javax.swing.JList<>();
        jScrollPane12 = new javax.swing.JScrollPane();
        Rate = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        Lar = new javax.swing.JRadioButton();
        Med = new javax.swing.JRadioButton();
        Sma = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        TC = new javax.swing.JLabel();
        CPI1 = new javax.swing.JLabel();
        TC1 = new javax.swing.JLabel();
        Quan = new javax.swing.JTextField();
        dne = new javax.swing.JRadioButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        Size = new javax.swing.JList<>();
        jScrollPane14 = new javax.swing.JScrollPane();
        Qty = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        a.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Order Snacks");

        Popc.setBackground(new java.awt.Color(0, 0, 0));
        Popc.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        Popc.setForeground(new java.awt.Color(255, 255, 255));
        Popc.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Caramel", "Tomato", "Salted", "Buttered", "Cheese&Mayo", "Plain" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Popc.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Popc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PopcMousePressed(evt);
            }
        });
        jScrollPane7.setViewportView(Popc);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/gree.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(16, 320));

        TA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TA.setForeground(new java.awt.Color(102, 255, 51));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Combo.setBackground(new java.awt.Color(0, 0, 0));
        Combo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        Combo.setForeground(new java.awt.Color(255, 255, 255));
        Combo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Nachos+A Drink", "Popcorn+A Drink", "Sandwich+A Drink", "Pizza+A Drink", "Burger+A Drink", "Hot Dog+A Drink" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Combo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Combo.setVisibleRowCount(6);
        Combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ComboMousePressed(evt);
            }
        });
        jScrollPane8.setViewportView(Combo);

        Snacks.setBackground(new java.awt.Color(0, 0, 0));
        Snacks.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        Snacks.setForeground(new java.awt.Color(255, 255, 255));
        Snacks.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Hot Dog", "Pizza", "Burger", "French Fries", "Sandwich", "Nachos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Snacks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Snacks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SnacksMousePressed(evt);
            }
        });
        jScrollPane9.setViewportView(Snacks);

        Drinks.setBackground(new java.awt.Color(0, 0, 0));
        Drinks.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        Drinks.setForeground(new java.awt.Color(255, 255, 255));
        Drinks.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Soft Drinks", "Iced Tea", "Hot Chocolate", "Cold Coffee", "Hot Coffee", "Bottled Water" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Drinks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Drinks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DrinksMousePressed(evt);
            }
        });
        jScrollPane10.setViewportView(Drinks);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Select Quantity:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Snacks:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Combos:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Popcorn:");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Amount:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Beverages:");

        CPI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CPI.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton3.setText("Remove Selection");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Bill.setBackground(new java.awt.Color(0, 0, 0));
        Bill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Bill.setForeground(new java.awt.Color(255, 255, 255));
        Bill.setModel(new DefaultListModel ());
        Bill.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BillMousePressed(evt);
            }
        });
        jScrollPane11.setViewportView(Bill);

        Rate.setBackground(new java.awt.Color(0, 0, 0));
        Rate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Rate.setForeground(new java.awt.Color(255, 255, 255));
        Rate.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Rate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RateMousePressed(evt);
            }
        });
        jScrollPane12.setViewportView(Rate);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add Item(s)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Lar.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Lar);
        Lar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Lar.setForeground(new java.awt.Color(255, 255, 255));
        Lar.setText("Large");
        Lar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LarMousePressed(evt);
            }
        });
        Lar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LarKeyPressed(evt);
            }
        });

        Med.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Med);
        Med.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Med.setForeground(new java.awt.Color(255, 255, 255));
        Med.setText("Medium");
        Med.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MedMousePressed(evt);
            }
        });

        Sma.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Sma);
        Sma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sma.setForeground(new java.awt.Color(255, 255, 255));
        Sma.setText("Small");
        Sma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SmaMousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Items:");

        TC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TC.setForeground(new java.awt.Color(204, 204, 204));

        CPI1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CPI1.setForeground(new java.awt.Color(204, 204, 204));
        CPI1.setText("Cost per Item: ");

        TC1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TC1.setForeground(new java.awt.Color(204, 204, 204));
        TC1.setText("Total Cost:  ");

        Quan.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                QuanCaretUpdate(evt);
            }
        });

        dne.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(dne);

        Size.setBackground(new java.awt.Color(0, 0, 0));
        Size.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Size.setForeground(new java.awt.Color(255, 255, 255));
        Size.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Size.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SizeMousePressed(evt);
            }
        });
        jScrollPane13.setViewportView(Size);

        Qty.setBackground(new java.awt.Color(0, 0, 0));
        Qty.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Qty.setForeground(new java.awt.Color(255, 255, 255));
        Qty.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Qty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                QtyMousePressed(evt);
            }
        });
        jScrollPane14.setViewportView(Qty);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Size:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Quan:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Total Cost:");

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/aaa.png"))); // NOI18N
        back.setToolTipText("Go back to Homepage and Logout");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/chu.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/chu.png"))); // NOI18N

        javax.swing.GroupLayout aLayout = new javax.swing.GroupLayout(a);
        a.setLayout(aLayout);
        aLayout.setHorizontalGroup(
            aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aLayout.createSequentialGroup()
                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE))
                    .addGroup(aLayout.createSequentialGroup()
                        .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(dne, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(182, 182, 182)
                                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(aLayout.createSequentialGroup()
                                        .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(TC1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(aLayout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(CPI, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TC, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(Quan, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(aLayout.createSequentialGroup()
                                        .addComponent(CPI1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aLayout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(100, 100, 100))))
                            .addGroup(aLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(32, 32, 32)
                                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(aLayout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(Lar)
                                .addGap(55, 55, 55)
                                .addComponent(Med)
                                .addGap(58, 58, 58)
                                .addComponent(Sma)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(289, 289, 289))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aLayout.createSequentialGroup()
                        .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(aLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(TA, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(aLayout.createSequentialGroup()
                                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(jButton3))
                                .addGap(18, 18, 18)
                                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aLayout.createSequentialGroup()
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(aLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(31, 31, 31)))
                        .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))))
        );
        aLayout.setVerticalGroup(
            aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(aLayout.createSequentialGroup()
                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48)
                        .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aLayout.createSequentialGroup()
                                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane8)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(aLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Med)
                                .addComponent(Sma))
                            .addComponent(Lar)))
                    .addGroup(aLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aLayout.createSequentialGroup()
                        .addComponent(dne, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aLayout.createSequentialGroup()
                        .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(CPI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CPI1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Quan))
                        .addGap(21, 21, 21)
                        .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(TC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TC1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
            .addGroup(aLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(8, 8, 8)
                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aLayout.createSequentialGroup()
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(aLayout.createSequentialGroup()
                        .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Double amoun = Double.parseDouble(TA.getText());
        Long showidl=Long.parseLong(showid);
        new OrderSummary(custid,showidl, amoun).setVisible(true);
         this.dispose();


    }//GEN-LAST:event_jButton1ActionPerformed
    DefaultListModel bill = new DefaultListModel();
    DefaultListModel sizes = new DefaultListModel();
    DefaultListModel amt = new DefaultListModel();
    DefaultListModel rate = new DefaultListModel();


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  try {

            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kleon", "root", "");

            String sql;

            sql = " select MovieName,MovieID,CustUsername,ShowId from temp";

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();
           custid=rs.getString("CustUsername");
           showid=rs.getString("ShowId");
           movieid=rs.getString("MovieID");
           
        } catch (ClassNotFoundException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error:  " + e.getMessage());

        }

        String p = "1";
        int qua;
        if (Quan.getText().equals("") || Integer.parseInt(Quan.getText()) < 1) {
            qua = 1;
        } else {
            qua = Integer.parseInt(Quan.getText());
        }
        if (Snacks.getSelectedIndex() == -1 && Drinks.getSelectedIndex() == -1 && Popc.getSelectedIndex() == -1 && Combo.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Please select an item first");
        } else if (Snacks.getSelectedIndex() > 5 || Drinks.getSelectedIndex() > 5 || Popc.getSelectedIndex() > 5 || Combo.getSelectedIndex() > 5) {
            JOptionPane.showMessageDialog(this, "Please select an item first");
        } else if (Sma.isSelected() == false && Med.isSelected() == false && Lar.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Please select the size!");
        } else if (qua < 1) {
            JOptionPane.showMessageDialog(this, "Please enter a Valid Quantity.");
        } else {
            int sn = Snacks.getSelectedIndex();
            int dr = Drinks.getSelectedIndex();
            int po = Popc.getSelectedIndex();
            int co = Combo.getSelectedIndex();
            int t = Math.max(Math.max(sn, dr), Math.max(po, co));
            if (sn == t) {
                p = Snacks.getSelectedValue();
            } else if (dr == t) {
                p = Drinks.getSelectedValue();
            } else if (po == t) {
                p = Popc.getSelectedValue();
            } else if (co == t) {
                p = Combo.getSelectedValue();
            }

            bill.addElement(p);
            Bill.setModel(bill);

            amt.addElement(qua);
            Qty.setModel(amt);
            String op = "M";
            if (Lar.isSelected()) {
                op = "L";
            } else if (Med.isSelected()) {
                op = "M";

            } else if (Sma.isSelected()) {
                op = "S";

            }
            sizes.addElement(op);
            Size.setModel(sizes);

            String tc = TC.getText();
            rate.addElement(tc);
            Rate.setModel(rate);
            amount = amount + Double.parseDouble(tc);
            TA.setText("" + amount);
            try {
                Class.forName("java.sql.DriverManager");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kleon", "root", "");

                String sql6;
                sql6 = "Insert into snacktally values('" + custid + "','" + p + "','" + op + "','" + movieid + "'," + qua + "," + showid + ")";
                System.out.println("" + sql6);
                System.out.println("" + sql6);
                Statement st = con.createStatement();
                st.executeUpdate(sql6);

            } catch (ClassNotFoundException | SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Error:  " + e.getMessage());
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SnacksMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SnacksMousePressed
        Drinks.clearSelection();
        Popc.clearSelection();
        Combo.clearSelection();
        dne.setSelected(true);
        CPI.setText("");
        TC.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_SnacksMousePressed

    private void DrinksMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrinksMousePressed
        Snacks.clearSelection();
        Popc.clearSelection();
        Combo.clearSelection();
        dne.setSelected(true);
        CPI.setText("");
        TC.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_DrinksMousePressed

    private void PopcMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopcMousePressed
        Snacks.clearSelection();
        Drinks.clearSelection();
        Combo.clearSelection();
        dne.setSelected(true);
        CPI.setText("");
        TC.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_PopcMousePressed

    private void ComboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboMousePressed
        Snacks.clearSelection();
        Drinks.clearSelection();
        Popc.clearSelection();
        dne.setSelected(true);
        CPI.setText("");
        TC.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_ComboMousePressed

    private void QuanCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_QuanCaretUpdate
        if (Lar.isSelected() == false && Med.isSelected() == false && Sma.isSelected() == false) {
        } else {
            int qua;
            if (Quan.getText().equals("") || Integer.parseInt(Quan.getText()) < 1) {
                qua = 1;
            } else {
                qua = Integer.parseInt(Quan.getText());
            }
            double cpi = Double.parseDouble(CPI.getText());
            double tc = cpi * qua;
            TC.setText("" + tc);
            System.out.println("" + tc);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_QuanCaretUpdate

    private void LarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_LarKeyPressed

    private void MedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedMousePressed
        int qua;

        int sn = Snacks.getSelectedIndex();
        String p = "1";
        int dr = Drinks.getSelectedIndex();
        int po = Popc.getSelectedIndex();
        int co = Combo.getSelectedIndex();
        int t = Math.max(Math.max(sn, dr), Math.max(po, co));
        if (sn == t) {
            p = Snacks.getSelectedValue();
        } else if (dr == t) {
            p = Drinks.getSelectedValue();
        } else if (po == t) {
            p = Popc.getSelectedValue();
        } else if (co == t) {
            p = Combo.getSelectedValue();
        }
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kleon", "root", "");
            Double size;
            String sql = "select SnackName,SnackPrice from snacks where SnackName='" + p + "'";
            System.out.println("" + sql);
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();

            size = 1.5;

            System.out.println("" + size);
            double cpi = Integer.parseInt(rs.getString("SnackPrice"));
            cpi = cpi * size;
            CPI.setText("" + cpi);

        } catch (ClassNotFoundException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error:  " + e.getMessage());
        }

        if (Quan.getText().equals("") || Integer.parseInt(Quan.getText()) < 1) {
            qua = 1;
        } else {
            qua = Integer.parseInt(Quan.getText());
        }
        double cpi = Double.parseDouble(CPI.getText());
        double tc = cpi * qua;
        TC.setText("" + tc);
        System.out.println("" + tc);// TODO add your handling code here:
    }//GEN-LAST:event_MedMousePressed

    private void SmaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SmaMousePressed
        int qua;

        int sn = Snacks.getSelectedIndex();
        String p = "1";
        int dr = Drinks.getSelectedIndex();
        int po = Popc.getSelectedIndex();
        int co = Combo.getSelectedIndex();
        int t = Math.max(Math.max(sn, dr), Math.max(po, co));
        if (sn == t) {
            p = Snacks.getSelectedValue();
        } else if (dr == t) {
            p = Drinks.getSelectedValue();
        } else if (po == t) {
            p = Popc.getSelectedValue();
        } else if (co == t) {
            p = Combo.getSelectedValue();
        }
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kleon", "root", "");
            Double size;
            String sql = "select SnackName,SnackPrice from snacks where SnackName='" + p + "'";
            System.out.println("" + sql);
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();

            size = 1.0;

            System.out.println("" + size);
            double cpi = Integer.parseInt(rs.getString("SnackPrice"));
            cpi = cpi * size;
            CPI.setText("" + cpi);

        } catch (ClassNotFoundException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error:  " + e.getMessage());
        }

        if (Quan.getText().equals("") || Integer.parseInt(Quan.getText()) < 1) {
            qua = 1;
        } else {
            qua = Integer.parseInt(Quan.getText());
        }
        double cpi = Double.parseDouble(CPI.getText());
        double tc = cpi * qua;
        TC.setText("" + tc);
        System.out.println("" + tc);// TODO add your handling code here:
    }//GEN-LAST:event_SmaMousePressed

    private void LarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LarMousePressed
        int qua;

        int sn = Snacks.getSelectedIndex();
        String p = "1";
        int dr = Drinks.getSelectedIndex();
        int po = Popc.getSelectedIndex();
        int co = Combo.getSelectedIndex();
        int t = Math.max(Math.max(sn, dr), Math.max(po, co));
        if (sn == t) {
            p = Snacks.getSelectedValue();
        } else if (dr == t) {
            p = Drinks.getSelectedValue();
        } else if (po == t) {
            p = Popc.getSelectedValue();
        } else if (co == t) {
            p = Combo.getSelectedValue();
        }
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kleon", "root", "");
            Double size;
            String sql = "select SnackName,SnackPrice from snacks where SnackName='" + p + "'";
            System.out.println("" + sql);
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.next();

            size = 2.0;

            System.out.println("" + size);
            double cpi = Integer.parseInt(rs.getString("SnackPrice"));
            cpi = cpi * size;
            CPI.setText("" + cpi);

        } catch (ClassNotFoundException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error:  " + e.getMessage());
        }        // TODO add your handling code here:

        if (Quan.getText().equals("") || Integer.parseInt(Quan.getText()) < 1) {
            qua = 1;
        } else {
            qua = Integer.parseInt(Quan.getText());
        }
        double cpi = Double.parseDouble(CPI.getText());
        double tc = cpi * qua;
        TC.setText("" + tc);
        System.out.println("" + tc);
    }//GEN-LAST:event_LarMousePressed

    private void BillMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillMousePressed
        int in = Bill.getSelectedIndex();
        Size.setSelectedIndex(in);
        Qty.setSelectedIndex(in);
        Rate.setSelectedIndex(in);
// TODO add your handling code here:
    }//GEN-LAST:event_BillMousePressed

    private void SizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SizeMousePressed
        int in = Size.getSelectedIndex();
        Bill.setSelectedIndex(in);
        Qty.setSelectedIndex(in);
        Rate.setSelectedIndex(in);        // TODO add your handling code here:
    }//GEN-LAST:event_SizeMousePressed

    private void QtyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QtyMousePressed
        int in = Qty.getSelectedIndex();
        Size.setSelectedIndex(in);
        Bill.setSelectedIndex(in);
        Rate.setSelectedIndex(in);        // TODO add your handling code here:
    }//GEN-LAST:event_QtyMousePressed

    private void RateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RateMousePressed
        int in = Rate.getSelectedIndex();
        Size.setSelectedIndex(in);
        Bill.setSelectedIndex(in);
        Qty.setSelectedIndex(in);// TODO add your handling code here:
    }//GEN-LAST:event_RateMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int rs = Bill.getSelectedIndex();

        if (rs == -1) {
        } else {
            Object qua = Qty.getSelectedValue();
            Object op = Size.getSelectedValue();
            Object p = Bill.getSelectedValue();
            System.out.println("" + p);
            System.out.println("" + op);
            try {
                Class.forName("java.sql.DriverManager");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kleon", "root", "");

                String sql7;
                sql7 = "delete from snacktally where CustId='" + custid + "' and SnackName='" + p + "' and Size='" + op + "' and MovieId='" + movieid + "' and Qty=" + qua + " and ShowId=" + showid;
                System.out.println("" + sql7);

                Statement st = con.createStatement();
                st.executeUpdate(sql7);
            } catch (ClassNotFoundException | SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Error:  " + e.getMessage());
            }
            amount = amount - Double.parseDouble(Rate.getSelectedValue());

            bill.remove(rs);
            Bill.setModel(bill);
            sizes.remove(rs);
            Size.setModel(sizes);
            amt.remove(rs);
            Qty.setModel(amt);
            rate.remove(rs);
            Rate.setModel(rate);

            TA.setText("" + amount);
        }
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3ActionPerformed

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        new Start().setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_backMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Snacks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Snacks().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Bill;
    private javax.swing.JLabel CPI;
    private javax.swing.JLabel CPI1;
    private javax.swing.JList<String> Combo;
    private javax.swing.JList<String> Drinks;
    private javax.swing.JRadioButton Lar;
    private javax.swing.JRadioButton Med;
    private javax.swing.JList<String> Popc;
    private javax.swing.JList<String> Qty;
    private javax.swing.JTextField Quan;
    private javax.swing.JList<String> Rate;
    private javax.swing.JList<String> Size;
    private javax.swing.JRadioButton Sma;
    private javax.swing.JList<String> Snacks;
    private javax.swing.JLabel TA;
    private javax.swing.JLabel TC;
    private javax.swing.JLabel TC1;
    private javax.swing.JPanel a;
    private javax.swing.JLabel back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton dne;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
