package Source;

import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author gargp
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public Start() {
        initComponents();
        jLabel7.setVisible(false);
        jLabel7.setEnabled(false);
        jLabel8.setVisible(false);
        jLabel8.setEnabled(false);
        jLabel9.setVisible(false);
        jLabel9.setEnabled(false);
        jLabel11.setVisible(false);
        jLabel11.setEnabled(false);
        jLabel.setVisible(false);
        jLabel.setEnabled(false);
   
        jLabel15.setVisible(false);
        jLabel15.setEnabled(false);
        jLabel3.setVisible(false);
        jLabel3.setEnabled(false);
/* try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kleon", "root", "");
            
            String sql;
            sql = "select * from temp";
            Statement st = con.createStatement();
            ResultSet rs =st.executeQuery(sql);
            if(!rs.next()){
                   System.out.println("no user");
            }
            else{
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
        } */
    }

    public Start(String user) {
        initComponents();
        jLabel7.setVisible(false);
        jLabel7.setEnabled(false);
        jLabel8.setVisible(false);
        jLabel8.setEnabled(false);
        jLabel9.setVisible(false);
        jLabel9.setEnabled(false);
        jLabel11.setVisible(false);
        jLabel11.setEnabled(false);
        jLabel.setVisible(false);
        jLabel.setEnabled(false);

        jLabel3.setVisible(false);
        jLabel3.setEnabled(false);
       
        jLabel15.setVisible(false);
        jLabel15.setEnabled(false);
     jLabel1.setText(jLabel1.getText()+" " + user);
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kleon", "root", "");
            String sql2 = "delete from temp";
            Statement st2 = con.createStatement();
            st2.executeUpdate(sql2);
            String sql;
            sql = "insert into temp(CustUsername) values('" + user + "')";
            Statement st = con.createStatement();
            st.executeUpdate(sql);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Ab = new javax.swing.JLabel();
        Cus = new javax.swing.JLabel();
        Emp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("- Login");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jLabel7);
        jLabel7.setBounds(140, 60, 70, 15);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("- Register");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jLabel8);
        jLabel8.setBounds(140, 80, 60, 15);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("- View Movies");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jLabel9);
        jLabel9.setBounds(340, 60, 90, 15);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("- Login");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jLabel11);
        jLabel11.setBounds(340, 80, 42, 15);

        jLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("- Book Tickets");
        jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMouseClicked(evt);
            }
        });
        jLayeredPane1.add(jLabel);
        jLabel.setBounds(340, 140, 90, 15);

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("View Offers");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jLabel14);
        jLabel14.setBounds(730, 20, 120, 30);

        Ab.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Ab.setForeground(new java.awt.Color(255, 255, 255));
        Ab.setText("About");
        Ab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AbMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Ab);
        Ab.setBounds(560, 20, 60, 30);

        Cus.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Cus.setForeground(new java.awt.Color(255, 255, 255));
        Cus.setText("Customer");
        Cus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CusMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Cus);
        Cus.setBounds(340, 20, 100, 30);

        Emp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Emp.setForeground(new java.awt.Color(255, 255, 255));
        Emp.setText("Employee");
        Emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Emp);
        Emp.setBounds(140, 20, 100, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/Untitled-2.png"))); // NOI18N
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(290, 370, 390, 210);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("- Register");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jLabel15);
        jLabel15.setBounds(340, 100, 60, 15);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hi, ");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(390, 340, 200, 40);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("- Add Reviews");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(340, 120, 90, 15);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SourceImages/Untitled-1.png"))); // NOI18N
        Back.setToolTipText("Click to exit.");
        Back.setAlignmentY(0.0F);
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Back);
        Back.setBounds(0, 0, 910, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        jLabel7.setVisible(false);
        jLabel7.setEnabled(false);
        jLabel8.setVisible(false);
        jLabel8.setEnabled(false);
        jLabel9.setVisible(false);
        jLabel9.setEnabled(false);
        jLabel11.setVisible(false);
        jLabel11.setEnabled(false);
        jLabel.setVisible(false);
        jLabel.setEnabled(false);
       
        jLabel15.setVisible(false);
        jLabel15.setEnabled(false);
jLabel3.setVisible(false);
        jLabel3.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_BackMouseClicked

    private void EmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpMouseClicked
        jLabel7.setVisible(true);
        jLabel7.setEnabled(true);
        jLabel8.setVisible(true);
        jLabel8.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_EmpMouseClicked

    private void CusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CusMouseClicked
        jLabel9.setVisible(true);
        jLabel9.setEnabled(true);
        jLabel15.setVisible(true);
        jLabel15.setEnabled(true);
        jLabel11.setVisible(true);
        jLabel11.setEnabled(true);
        jLabel.setVisible(true);
        jLabel.setEnabled(true); 
        jLabel3.setVisible(true);
        jLabel3.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_CusMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        new EmployeeLogin().setVisible(true);  
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        new EmloyeeRegistry().setVisible(true);    
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        new MovieList().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        new CustomerLogin().setVisible(true); 
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMouseClicked

    String user = jLabel1.getText();
    
        if (user.equals("Hi, ")) {
            new CustomerLogin().setVisible(true);
            this.dispose();
        } else {
            String custid=user.substring(5);
            new BookTicket(custid).setVisible(true);
            this.dispose();
        }    
// TODO add your handling code here:
    }//GEN-LAST:event_jLabelMouseClicked

    private void AbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbMouseClicked
        new About().setVisible(true);   
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_AbMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        new ViewOffers().setVisible(true); 
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        new CustomerRegistry().setVisible(true);     
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
    String user = jLabel1.getText();
    
        if (user.equals("Hi, ")) {
            new CustomerLogin().setVisible(true);
            this.dispose();
        } else {
            new AddReview().setVisible(true);
            this.dispose();
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {                                            // TODO add your handling code here:
    }

    private void jLabe31MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ab;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Cus;
    private javax.swing.JLabel Emp;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
