 package Source;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author gargp
 */
public class ViewReviews extends javax.swing.JFrame {

    int a = 1, b = 2, c = 3;

    public ViewReviews() {
        initComponents();
    }

    /**
     * Creates new form ViewReviews
     */
    public ViewReviews(int mov) {
        initComponents();
        somepoint:
        {

            try {
                jLabel5.setText("" + mov);
                Class.forName("java.sql.DriverManager");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kleon", "root", "");

                String sql, sql2, sql3;

                sql = "select CustUsername,ReviewText from customer,reviews where reviews.CustId=customer.CustUsername and MovRevId in (" + a + "," + b + "," + c + ") and MovieId=" + mov;
                sql3 = "select MovieName from movies where MovieId=" + mov;
                sql2 = "select count(*) from customer,reviews where reviews.CustId=customer.CustUsername and MovieId=" + mov;

                System.out.println("" + sql);
                System.out.println("" + sql3);

                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);

                Statement st3 = con.createStatement();
                ResultSet rs3 = st3.executeQuery(sql3);

                Statement st2 = con.createStatement();
                ResultSet rs2 = st2.executeQuery(sql2);
                rs2.next();
                int d = Integer.parseInt(rs2.getString("count(*)"));
                d = d - 3;
                jLabel1.setVisible(false);
                jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
                jLabel1.setText("" + d);


                rs3.next();
                Mo.setText(rs3.getString("MovieName"));
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(null, "No Reviews Yet");
                } else {
                    R1.setText(rs.getString("ReviewText"));
                    N1.setText(rs.getString("CustUsername"));
                    if (!rs.next()) {
                        R2.setText("No more Reviews");
                        N2.setText("");
                        R2.setEnabled(false);
                        N2.setVisible(false);
                    } else {
                        R2.setText(rs.getString("ReviewText"));
                        N2.setText(rs.getString("CustUsername"));
                    }
                    if (!rs.next()) {
                        R3.setText("No more Reviews");
                        N3.setText("");
                        R3.setEnabled(false);
                        N3.setVisible(false);
                    } else {
                        R3.setText(rs.getString("ReviewText"));
                        N3.setText(rs.getString("CustUsername"));
                    }

                    a += 3;
                    b += 3;
                    c += 3;
                }

            } catch (ClassNotFoundException | SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Error:  " + e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        Mo = new javax.swing.JLabel();
        N1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        R2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        R3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        R1 = new javax.swing.JTextArea();
        N2 = new javax.swing.JLabel();
        N3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Mo1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Mo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Mo.setForeground(new java.awt.Color(255, 255, 255));
        Mo.setText("Movie Name");

        N1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        N1.setForeground(new java.awt.Color(255, 255, 255));

        R2.setEditable(false);
        R2.setColumns(20);
        R2.setRows(5);
        jScrollPane1.setViewportView(R2);

        R3.setEditable(false);
        R3.setColumns(20);
        R3.setRows(5);
        jScrollPane2.setViewportView(R3);

        R1.setEditable(false);
        R1.setColumns(20);
        R1.setFont(new java.awt.Font("Open Sans Semibold", 0, 13)); // NOI18N
        R1.setRows(5);
        jScrollPane4.setViewportView(R1);

        N2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        N2.setForeground(new java.awt.Color(255, 255, 255));

        N3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        N3.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Load More Reviews >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFocusable(false);
        jLabel1.setInheritsPopupMenu(false);
        jLabel1.setRequestFocusEnabled(false);
        jLabel1.setVerifyInputWhenFocusTarget(false);

        jLabel2.setText("4");
        jLabel2.setFocusable(false);
        jLabel2.setInheritsPopupMenu(false);
        jLabel2.setRequestFocusEnabled(false);
        jLabel2.setVerifyInputWhenFocusTarget(false);

        jLabel3.setText("5");
        jLabel3.setFocusable(false);
        jLabel3.setInheritsPopupMenu(false);
        jLabel3.setRequestFocusEnabled(false);
        jLabel3.setVerifyInputWhenFocusTarget(false);

        jLabel4.setText("6");
        jLabel4.setFocusable(false);
        jLabel4.setInheritsPopupMenu(false);
        jLabel4.setRequestFocusEnabled(false);
        jLabel4.setVerifyInputWhenFocusTarget(false);

        Mo1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Mo1.setForeground(new java.awt.Color(255, 255, 255));
        Mo1.setText("Reviews For:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Mo1)
                        .addGap(18, 18, 18)
                        .addComponent(Mo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(109, 109, 109))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jButton1)
                        .addGap(144, 144, 144)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(N2)
                            .addComponent(N3)
                            .addComponent(N1))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(772, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(20, 20, 20)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(782, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(772, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(20, 20, 20)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Mo1)
                    .addComponent(Mo)
                    .addComponent(jLabel5))
                .addGap(41, 41, 41)
                .addComponent(N1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(N2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(N3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jLabel2)
                    .addContainerGap(542, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jLabel3)
                    .addContainerGap(532, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(jLabel4)
                    .addContainerGap(522, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kleon", "root", "");
            /*
             * Added if else statements for number of reviews, need to add Movie
             * selector(edit sql queries too), test the number of reviews thingy
             * and use constructor to get the mvoie id from previous form ,make
             * sure to change the jlabel(movie name)
             */
            String sql, sql2;
            int e, f, g;
            e = Integer.parseInt(jLabel2.getText());
            f = Integer.parseInt(jLabel3.getText());
            g = Integer.parseInt(jLabel4.getText());
            int mov = Integer.parseInt(jLabel5.getText());
            sql = "select ReviewText,CustUsername from customer,reviews where reviews.CustId=customer.CustUsername and MovRevId in (" + e + "," + f + "," + g + ") and MovieId=" + mov;



            System.out.println("" + sql);
            int d = Integer.parseInt(jLabel1.getText());

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            System.out.println("" + jLabel2.getText());
            System.out.println("" + jLabel3.getText());
            System.out.println("" + jLabel4.getText());

            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "No More Reviews");

            } else {
                rs.previous();
                if (!rs.next()) {
                    R1.setText("No more Reviews");
                    N1.setText("");
                    R1.setEnabled(false);
                    N1.setVisible(false);

                } else {
                    R1.setText(rs.getString("ReviewText"));
                    N1.setText(rs.getString("CustUsername"));

                    e += 3;
                    jLabel2.setText("" + e);

                }

                if (!rs.next()) {
                    R2.setText("No more Reviews");
                    N2.setText("");
                    R2.setEnabled(false);
                    N2.setVisible(false);
                } else {
                    R2.setText(rs.getString("ReviewText"));
                    N2.setText(rs.getString("CustUsername"));

                    f += 3;
                    jLabel3.setText("" + f);

                }


                if (!rs.next()) {
                    R3.setText("No more Reviews");
                    N3.setText("");
                    R3.setEnabled(false);
                    N3.setVisible(false);
                } else {
                    R3.setText(rs.getString("ReviewText"));
                    N3.setText(rs.getString("CustUsername"));

                    g += 3;
                    jLabel4.setText("" + g);

                }
            }
            d = d - 3;
            jLabel1.setText("" + d);


        } catch (ClassNotFoundException | SQLException | NumberFormatException | HeadlessException e) {

            if (e.getMessage().equals("After end of result set")) {
            } else {
                JOptionPane.showMessageDialog(null, "Error:  " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new Start().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;




                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReviews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new ViewReviews().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mo;
    private javax.swing.JLabel Mo1;
    private javax.swing.JLabel N1;
    private javax.swing.JLabel N2;
    private javax.swing.JLabel N3;
    private javax.swing.JTextArea R1;
    private javax.swing.JTextArea R2;
    private javax.swing.JTextArea R3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
